
"""
灰色关联分析 (Grey Relational Analysis, GRA)

用于分析多因素系统中各因素与参考序列的关联程度。
适用于小样本、贫信息系统。

使用方法:
    from grey_relational_analysis import GreyRelationalAnalysis

    # 准备数据
    reference = np.array([100, 120, 150, 180, 220])  # 参考序列
    comparison = np.array([                          # 比较序列
        [50, 60, 80, 100, 130],
        [80, 78, 75, 72, 70]
    ])

    # 创建分析器并执行分析
    gra = GreyRelationalAnalysis(rho=0.5)
    gra.fit(reference, comparison, 
            preprocess_method='initial',
            sequence_names=['因素1', '因素2'])

    # 获取结果
    degrees = gra.get_correlation_degrees()  # 关联度
    ranking = gra.get_ranking()                # 排序

    # 打印报告和可视化
    gra.print_report()
    gra.plot()

Author: Generated by Kimi
Date: 2026-07-21
Version: 1.0
"""

import numpy as np


class GreyRelationalAnalysis:
    """
    灰色关联分析类

    实现完整的灰色关联分析流程，包括数据预处理、关联系数计算、
    关联度计算和结果可视化。

    Parameters
    ----------
    rho : float, default=0.5
        分辨系数，取值范围 (0, 1)。rho 越小，分辨力越大；通常取 0.5。
    """

    def __init__(self, rho=0.5):
        """
        初始化灰色关联分析器

        Parameters
        ----------
        rho : float, default=0.5
            分辨系数，取值范围 (0, 1)。
        """
        if not 0 < rho < 1:
            raise ValueError("分辨系数 rho 必须在 (0, 1) 范围内")

        self.rho = rho
        self.reference_sequence = None       # 参考序列（母序列）
        self.comparison_sequences = None     # 比较序列（子序列）
        self.processed_data = None           # 预处理后的数据
        self.correlation_coefficients = None  # 关联系数
        self.correlation_degrees = None        # 关联度
        self.sequence_names = None           # 序列名称

    # ==================== 1. 数据预处理 ====================

    def _initial_value_processing(self, data):
        """
        初值化处理：每个序列除以第一个元素

        x'(k) = x(k) / x(1)

        适用于序列起点有意义的情况，如增长率分析。

        Parameters
        ----------
        data : ndarray, shape (n_sequences, n_time_points)
            原始数据矩阵

        Returns
        -------
        processed : ndarray
            初值化处理后的数据
        """
        return data / data[:, 0:1]

    def _mean_value_processing(self, data):
        """
        均值化处理：每个序列除以其均值

        x'(k) = x(k) / mean(x)

        适用于序列波动较大的情况，消除量纲影响。

        Parameters
        ----------
        data : ndarray, shape (n_sequences, n_time_points)
            原始数据矩阵

        Returns
        -------
        processed : ndarray
            均值化处理后的数据
        """
        return data / np.mean(data, axis=1, keepdims=True)

    def _range_processing(self, data):
        """
        极差变换（归一化）：映射到 [0, 1] 区间

        x'(k) = [x(k) - min(x)] / [max(x) - min(x)]

        适用于需要统一量纲的情况。

        Parameters
        ----------
        data : ndarray, shape (n_sequences, n_time_points)
            原始数据矩阵

        Returns
        -------
        processed : ndarray
            极差变换后的数据
        """
        min_vals = np.min(data, axis=1, keepdims=True)
        max_vals = np.max(data, axis=1, keepdims=True)
        return (data - min_vals) / (max_vals - min_vals + 1e-10)

    def preprocess(self, data, method='initial'):
        """
        数据预处理（无量纲化）

        消除不同量纲对分析结果的影响。

        Parameters
        ----------
        data : ndarray, shape (n_sequences, n_time_points)
            原始数据矩阵，每行代表一个序列
        method : str, default='initial'
            预处理方法：
            - 'initial': 初值化，x'(k) = x(k)/x(1)
            - 'mean': 均值化，x'(k) = x(k)/mean(x)
            - 'range': 极差变换，映射到 [0,1]

        Returns
        -------
        processed : ndarray
            预处理后的数据
        """
        if method == 'initial':
            return self._initial_value_processing(data)
        elif method == 'mean':
            return self._mean_value_processing(data)
        elif method == 'range':
            return self._range_processing(data)
        else:
            raise ValueError(f"未知的预处理方法: {method}，可选: 'initial', 'mean', 'range'")

    # ==================== 2. 计算关联系数 ====================

    def _calculate_difference(self, reference, comparison):
        """
        计算参考序列与比较序列的绝对差值

        Δ_i(k) = |x_0(k) - x_i(k)|

        Parameters
        ----------
        reference : ndarray, shape (n_time_points,)
            参考序列
        comparison : ndarray, shape (n_sequences, n_time_points)
            比较序列矩阵

        Returns
        -------
        differences : ndarray, shape (n_sequences, n_time_points)
            绝对差值矩阵
        """
        return np.abs(reference - comparison)

    def _calculate_correlation_coefficients(self, differences):
        """
        计算关联系数

        ξ_i(k) = [min_min_Δ + ρ·max_max_Δ] / [Δ_i(k) + ρ·max_max_Δ]

        其中:
        - min_min_Δ = min_i min_k |x_0(k) - x_i(k)|  (两级最小差)
        - max_max_Δ = max_i max_k |x_0(k) - x_i(k)|  (两级最大差)
        - ρ 为分辨系数

        Parameters
        ----------
        differences : ndarray, shape (n_sequences, n_time_points)
            绝对差值矩阵

        Returns
        -------
        coefficients : ndarray, shape (n_sequences, n_time_points)
            关联系数矩阵，取值范围 [0, 1]
        """
        # 两级最小差和两级最大差
        min_min_delta = np.min(differences)
        max_max_delta = np.max(differences)

        # 计算关联系数
        numerator = min_min_delta + self.rho * max_max_delta
        denominator = differences + self.rho * max_max_delta

        coefficients = numerator / denominator

        return coefficients

    # ==================== 3. 计算关联度 ====================

    def _calculate_correlation_degrees(self, coefficients):
        """
        计算关联度（关联系数的平均值）

        γ_i = (1/n) * Σ_{k=1}^{n} ξ_i(k)

        关联度反映整体关联程度，取值范围 [0, 1]。

        Parameters
        ----------
        coefficients : ndarray, shape (n_sequences, n_time_points)
            关联系数矩阵

        Returns
        -------
        degrees : ndarray, shape (n_sequences,)
            关联度数组
        """
        return np.mean(coefficients, axis=1)

    # ==================== 4. 主分析流程 ====================

    def fit(self, reference_sequence, comparison_sequences, 
            preprocess_method='initial', sequence_names=None):
        """
        执行灰色关联分析

        完整流程：数据预处理 → 计算差值 → 计算关联系数 → 计算关联度

        Parameters
        ----------
        reference_sequence : array-like, shape (n_time_points,)
            参考序列（母序列），反映系统行为特征。
            例如：销量、产值、效益等目标指标。
        comparison_sequences : array-like, shape (n_sequences, n_time_points)
            比较序列（子序列），每行代表一个影响因素。
            例如：广告投入、价格、渠道数量等。
        preprocess_method : str, default='initial'
            预处理方法：'initial'(初值化), 'mean'(均值化), 'range'(极差变换)
        sequence_names : list of str, optional
            比较序列的名称，用于结果展示。如果不提供，自动生成默认名称。

        Returns
        -------
        self : GreyRelationalAnalysis
            返回自身，支持链式调用

        Examples
        --------
        >>> gra = GreyRelationalAnalysis(rho=0.5)
        >>> gra.fit([100, 120, 150], [[50, 60, 80], [80, 78, 75]],
        ...         sequence_names=['广告', '价格'])
        """
        # 转换为 numpy 数组
        self.reference_sequence = np.array(reference_sequence, dtype=float)
        self.comparison_sequences = np.array(comparison_sequences, dtype=float)

        # 数据校验
        if self.reference_sequence.ndim != 1:
            raise ValueError("参考序列必须是一维数组")
        if self.comparison_sequences.ndim != 2:
            raise ValueError("比较序列必须是二维数组")
        if self.reference_sequence.shape[0] != self.comparison_sequences.shape[1]:
            raise ValueError(
                f"参考序列长度({self.reference_sequence.shape[0]})与"
                f"比较序列时间点数({self.comparison_sequences.shape[1]})不一致"
            )

        # 保存序列名称
        if sequence_names is not None:
            if len(sequence_names) != self.comparison_sequences.shape[0]:
                raise ValueError(
                    f"序列名称数量({len(sequence_names)})与"
                    f"比较序列数量({self.comparison_sequences.shape[0]})不一致"
                )
            self.sequence_names = list(sequence_names)
        else:
            self.sequence_names = [f"因素{i+1}" for i in range(self.comparison_sequences.shape[0])]

        # 合并数据并预处理
        all_data = np.vstack([self.reference_sequence, self.comparison_sequences])
        self.processed_data = self.preprocess(all_data, method=preprocess_method)

        # 分离处理后的参考序列和比较序列
        processed_reference = self.processed_data[0]
        processed_comparison = self.processed_data[1:]

        # 计算绝对差值
        differences = self._calculate_difference(processed_reference, processed_comparison)

        # 计算关联系数
        self.correlation_coefficients = self._calculate_correlation_coefficients(differences)

        # 计算关联度
        self.correlation_degrees = self._calculate_correlation_degrees(self.correlation_coefficients)

        return self

    # ==================== 5. 结果输出 ====================

    def get_correlation_degrees(self):
        """
        获取关联度结果

        返回各因素与参考序列的关联度，按关联度降序排列。

        Returns
        -------
        result : dict
            {因素名称: 关联度}，按关联度降序排列

        Raises
        ------
        ValueError
            如果未先调用 fit() 方法
        """
        if self.correlation_degrees is None:
            raise ValueError("请先调用 fit() 方法进行分析")

        result = {
            name: float(degree) 
            for name, degree in zip(self.sequence_names, self.correlation_degrees)
        }
        # 按关联度降序排列
        result = dict(sorted(result.items(), key=lambda x: x[1], reverse=True))
        return result

    def get_correlation_coefficients(self):
        """
        获取关联系数矩阵

        关联系数反映每个时间点上参考序列与比较序列的关联程度。

        Returns
        -------
        coefficients : ndarray, shape (n_sequences, n_time_points)
            关联系数矩阵，每行对应一个因素，每列对应一个时间点

        Raises
        ------
        ValueError
            如果未先调用 fit() 方法
        """
        if self.correlation_coefficients is None:
            raise ValueError("请先调用 fit() 方法进行分析")
        return self.correlation_coefficients

    def get_ranking(self):
        """
        获取因素排序结果

        按关联度从高到低排序，返回排名信息。

        Returns
        -------
        ranking : list of tuple
            [(排名, 因素名称, 关联度), ...]

        Raises
        ------
        ValueError
            如果未先调用 fit() 方法
        """
        if self.correlation_degrees is None:
            raise ValueError("请先调用 fit() 方法进行分析")

        sorted_indices = np.argsort(self.correlation_degrees)[::-1]
        ranking = []
        for rank, idx in enumerate(sorted_indices, 1):
            ranking.append((rank, self.sequence_names[idx], float(self.correlation_degrees[idx])))
        return ranking

    def print_report(self):
        """
        打印详细的分析报告

        包含关联系数矩阵、关联度排序和结论。
        """
        if self.correlation_degrees is None:
            raise ValueError("请先调用 fit() 方法进行分析")

        print("=" * 60)
        print("           灰色关联分析报告 (Grey Relational Analysis)")
        print("=" * 60)
        print(f"分辨系数 ρ = {self.rho}")
        print(f"时间点数 n = {self.reference_sequence.shape[0]}")
        print(f"比较因素数 m = {self.comparison_sequences.shape[0]}")
        print("-" * 60)

        print("\n【1. 关联系数矩阵】")
        print(f"{'因素':<12}", end="")
        for k in range(self.correlation_coefficients.shape[1]):
            print(f"t{k+1:<8}", end="")
        print()

        for i, name in enumerate(self.sequence_names):
            print(f"{name:<12}", end="")
            for k in range(self.correlation_coefficients.shape[1]):
                print(f"{self.correlation_coefficients[i, k]:<8.4f}", end="")
            print()

        print("\n【2. 关联度及排序】")
        print(f"{'排名':<6}{'因素':<15}{'关联度':<12}{'关联程度'}")
        print("-" * 45)

        ranking = self.get_ranking()
        for rank, name, degree in ranking:
            if degree >= 0.9:
                level = "极强关联"
            elif degree >= 0.8:
                level = "强关联"
            elif degree >= 0.7:
                level = "较强关联"
            elif degree >= 0.6:
                level = "中等关联"
            else:
                level = "弱关联"
            print(f"{rank:<6}{name:<15}{degree:<12.4f}{level}")

        print("\n【3. 结论】")
        top_factor = ranking[0][1]
        top_degree = ranking[0][2]
        print(f"   与参考序列关联度最高的因素是: {top_factor} (γ = {top_degree:.4f})")
        print(f"   各因素关联度总和: {np.sum(self.correlation_degrees):.4f}")
        print(f"   平均关联度: {np.mean(self.correlation_degrees):.4f}")
        print("=" * 60)

    # ==================== 6. 可视化 ====================

    def plot(self, figsize=(12, 8), save_path=None):
        """
        绘制灰色关联分析可视化图表

        生成 2x2 的子图，包含：
        1. 预处理后序列曲线
        2. 关联系数变化曲线
        3. 各因素关联度柱状图
        4. 关联度排序图

        Parameters
        ----------
        figsize : tuple, default=(12, 8)
            图表尺寸 (宽, 高)
        save_path : str, optional
            保存路径，如果为 None 则显示图表

        Returns
        -------
        fig : matplotlib.figure.Figure
            图表对象
        """
        import matplotlib.pyplot as plt

        plt.rcParams['font.sans-serif'] = ['SimHei', 'Microsoft YaHei', 'DejaVu Sans']
        plt.rcParams['axes.unicode_minus'] = False

        if self.processed_data is None:
            raise ValueError("请先调用 fit() 方法进行分析")

        fig, axes = plt.subplots(2, 2, figsize=figsize)

        # 1. 预处理后的序列曲线
        ax1 = axes[0, 0]
        time_points = np.arange(1, self.processed_data.shape[1] + 1)
        ax1.plot(time_points, self.processed_data[0], 'k-', linewidth=2, 
                 label='参考序列', marker='o')
        for i, name in enumerate(self.sequence_names):
            ax1.plot(time_points, self.processed_data[i+1], '--', 
                    label=name, marker='s', alpha=0.7)
        ax1.set_title('预处理后序列曲线')
        ax1.set_xlabel('时间点')
        ax1.set_ylabel('相对值')
        ax1.legend(loc='best', fontsize=8)
        ax1.grid(True, alpha=0.3)

        # 2. 关联系数曲线
        ax2 = axes[0, 1]
        for i, name in enumerate(self.sequence_names):
            ax2.plot(time_points, self.correlation_coefficients[i], 
                    label=name, marker='o')
        ax2.set_title('关联系数变化曲线')
        ax2.set_xlabel('时间点')
        ax2.set_ylabel('关联系数')
        ax2.legend(loc='best', fontsize=8)
        ax2.grid(True, alpha=0.3)

        # 3. 关联度柱状图
        ax3 = axes[1, 0]
        colors = plt.cm.RdYlGn(np.linspace(0.3, 0.9, len(self.sequence_names)))
        bars = ax3.barh(self.sequence_names, self.correlation_degrees, color=colors)
        ax3.set_xlim(0, 1)
        ax3.set_title('各因素关联度')
        ax3.set_xlabel('关联度 γ')
        for bar, val in zip(bars, self.correlation_degrees):
            ax3.text(val + 0.01, bar.get_y() + bar.get_height()/2, 
                    f'{val:.4f}', va='center', fontsize=9)
        ax3.grid(True, alpha=0.3, axis='x')

        # 4. 关联度排序图
        ax4 = axes[1, 1]
        ranking = self.get_ranking()
        names = [r[1] for r in ranking]
        degrees = [r[2] for r in ranking]
        colors_sorted = plt.cm.RdYlGn(np.linspace(0.3, 0.9, len(names)))[::-1]
        bars = ax4.bar(range(len(names)), degrees, color=colors_sorted)
        ax4.set_xticks(range(len(names)))
        ax4.set_xticklabels(names, rotation=45, ha='right')
        ax4.set_ylim(0, 1)
        ax4.set_title('关联度排序')
        ax4.set_ylabel('关联度 γ')
        for bar, val in zip(bars, degrees):
            ax4.text(bar.get_x() + bar.get_width()/2, val + 0.01, 
                    f'{val:.4f}', ha='center', fontsize=9)
        ax4.grid(True, alpha=0.3, axis='y')

        plt.tight_layout()

        if save_path:
            plt.savefig(save_path, dpi=300, bbox_inches='tight')
            print(f"图表已保存至: {save_path}")

        return fig


# ==================== 使用示例 ====================

if __name__ == "__main__":
    import numpy as np

    # 示例数据：某产品销量与三个影响因素
    # 参考序列：销量（万件）
    sales = np.array([100, 120, 150, 180, 220, 260, 300])

    # 比较序列：
    # 因素1：广告投入（万元）
    # 因素2：价格（元）
    # 因素3：渠道数量（个）
    factors = np.array([
        [50, 60, 80, 100, 130, 160, 200],    # 广告投入
        [80, 78, 75, 72, 70, 68, 65],        # 价格
        [20, 25, 30, 35, 42, 50, 60]         # 渠道数量
    ])

    factor_names = ['广告投入', '价格', '渠道数量']

    # 创建分析器并执行分析
    gra = GreyRelationalAnalysis(rho=0.5)
    gra.fit(sales, factors, 
            preprocess_method='initial',
            sequence_names=factor_names)

    # 打印报告
    gra.print_report()

    # 获取结果
    print("\n关联度字典:")
    print(gra.get_correlation_degrees())

    print("\n排序结果:")
    for rank, name, degree in gra.get_ranking():
        print(f"  第{rank}名: {name} (γ = {degree:.4f})")